Traceback (most recent call last):
  File "/home/jeremy/banksh/ideas/exceptions.tests/nothing.bash", line 342
  File "/home/jeremy/banksh/ideas/exceptions.tests/nothing.bash", line 331, in examples
  File "/home/jeremy/banksh/ideas/exceptions.tests/nothing.bash", line 338, in example-1
ExampleError: oh noes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeremy/banksh/ideas/exceptions.tests/nothing.bash", line 342
  File "/home/jeremy/banksh/ideas/exceptions.tests/nothing.bash", line 333, in examples
UhOhError: caught an exception (ExampleError: oh noes), what do I do? oh no!
